update:
	python update.py data/<archivo>

installdb:
	mysql -u root --password="PASS" < initialize.sql
	python update.py data/<archivo>
	touch ../comisiones/delete
	rm -r ../comisiones/*
	touch ../scratch/delete
	rm -r ../scratch/*
