update:
	python update.py data/<archivo>

cleandb:
	mysql -u root --password="PASS" < initialize.sql
	python update.py data/<archivo>
	touch ../comisiones/delete
	rm -r ../comisiones/*
	touch ../scratch/delete
	rm -r ../scratch/*
	cp resoluciones.txt.ini resoluciones.txt
	chown -R www-data.www-data .
